# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccb84e68c07dd8134ac6c7065fa5a1a991b2c46646a8b7606b6787c8984ea33fa4e46101029fb1246ed0581e1f7b459e2269297082fa0e4866c79eabd939ea9c

test:
  secret_key_base: 947552482161ae7b83f46f2d048cc7bdffe12b737259e69310c72d9b1caacaf1de4c0b1e8bd578b438de5ba3830df71ea12ec8bc6b22197556f36aa627c2b356

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
